[package]
name = "wasm-clock"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.18"
js-sys = "0.3"
gloo-timers = "0.2"